# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zhenyu0519.github.io
date_format: "ordinal"
title: 杰弗里 · 时光博客(Jeffrey's Blog)
subtitle: "深情不及久伴"
description: "Personal Blog"
keywords: Diary, Jeffrey, Techonlogy, github pages, Post, North America, Leetcode, Interview
timezone: America/Vancouver
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Jeffrey
organization: 
organization_url: 
github_username: zhenyu0519
location: Vancouver, Canada
email: zhenyu0519@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /open-source/
    label: Github Repos

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-seo-tag

repository: zhenyu0519/zhenyu0519.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhenyu0519
    repo: zhenyu0519.github.io
    oauth:
        client_id: 4cef70907f5b36353d59
        client_secret: 94b120bec4f51b07c796df03ad3ece5a99f71ed6
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhenyu0519
    repo: zhenyu0519.github.io
    clientID: 4cef70907f5b36353d59
    clientSecret: 94b120bec4f51b07c796df03ad3ece5a99f71ed6
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-113380665-1
